version: '3.2'

services:
  project:
    image: ghcr.io/mayraamaral/course-project:main
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    ports:
      - "8080:8080"
    volumes:
      - course_project:/usr/app
    depends_on:
      - db
    networks:
      - npm_public
  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: app
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - npm_public
volumes:
  course_project:
    external: true
networks:
  npm_public:
    external: true